class Atoms:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def __deepcopy__(self, memo: dict[int, object]) -> Atoms: ...
    def set_model_number(self, number: int) -> None: ...
    def from_numpy(self, matrix: object) -> None: ...
    def add_side_chain_centers(self) -> None: ...
    def extend(self, other: Atoms) -> None: ...
    def save_to_pdb(
        self, filename: str, bar_msg: str = "", header: str = ""
    ) -> None: ...
